// ============================================================
// HexCore Rellic Decompiler (EXPERIMENTAL)
// File: wwzRetailEgs.exe
// Address: 0x140000000
// Architecture: amd64
// Generated: 2026-02-23T05:58:10.737Z
// ============================================================
// WARNING: This code was automatically generated by Rellic.
// It is NOT compilable C — it is pseudo-C for analysis purposes.
// ============================================================
// Pseudo-C generated by HexCore Rellic
// Module: <string>
// Target: x86_64-unknown-windows-msvc-coff

#include <stdint.h>

void * lifted_5368709120(void * state, uint64_t program_counter, void * memory) {
	// Register variables
	uint64_t AL;
	uint64_t R10;
	uint64_t RAX;
	uint64_t RBX;


bb_0:
	NEXT_PC = program_counter;
	t0 = NEXT_PC;
	PC = t0;
	t1 = t0 + 2;
	NEXT_PC = t1;
	t2 = *(uint64_t*)RSP; RSP += 8;  // POP
	t4 = NEXT_PC;
	PC = t4;
	t5 = t4 + 1;
	NEXT_PC = t5;
	/* nop */  // NOP_IMPL
	t8 = NEXT_PC;
	PC = t8;
	t9 = t8 + 2;
	NEXT_PC = t9;
	t10 = RBX;
	t11 = RBX;
	t12 = AL;
	t13 = (uint64_t)t12;
	t14 = t10 + t11;  // ADD
	t16 = NEXT_PC;
	PC = t16;
	t17 = t16 + 2;
	NEXT_PC = t17;
	t18 = RAX;
	t19 = RAX;
	t20 = AL;
	t21 = (uint64_t)t20;
	t22 = t18 + t19;  // ADD
	t24 = NEXT_PC;
	PC = t24;
	t25 = t24 + 3;
	NEXT_PC = t25;
	t26 = RAX;
	t27 = RAX;
	t28 = t27 * 1;
	t29 = t26 + t28;
	t30 = RAX;
	t31 = RAX;
	t32 = t31 * 1;
	t33 = t30 + t32;
	t34 = AL;
	t35 = (uint64_t)t34;
	t36 = t29 + t33;  // ADD
	t38 = NEXT_PC;
	PC = t38;
	t39 = t38 + 2;
	NEXT_PC = t39;
	t40 = RAX;
	t41 = RAX;
	t42 = AL;
	t43 = (uint64_t)t42;
	t44 = t40 + t41;  // ADD
	return memory;
}

