/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * The Helix decompilation engine.
 *
 * Usage from TypeScript:
 * ```typescript
 * import { HelixEngine, Architecture } from '@hexcore/helix';
 *
 * const engine = new HelixEngine(Architecture.X86_64);
 * const result = engine.decompile(binaryBuffer, 0x400000n, 0x401000n);
 * console.log(result.source);
 * engine.dispose();
 * ```
 */
export declare class HelixEngine {
  /** Create a new Helix engine instance for the specified architecture. */
  constructor(arch: Architecture)
  /** Get the engine version string. */
  version(): string
  /** Get the target architecture name. */
  architecture(): string
  /**
   * Decompile a binary buffer starting at the given entry address.
   *
   * - `data`: Raw binary data (Buffer)
   * - `base_address`: Base virtual address where the data is loaded (BigInt)
   * - `entry_address`: Entry point address to start decompilation (BigInt)
   */
  decompile(data: Buffer, baseAddress: bigint, entryAddress: bigint): DecompileResult
  /** Release engine resources. The engine cannot be used after this call. */
  dispose(): void
  /**
   * Decompile Remill LLVM IR text into pseudo-C source code.
   *
   * This method takes the raw IR text output from HexCore's Remill lifter
   * and transforms it into human-readable decompiled code.
   *
   * - `ir_text`: The LLVM IR text from `hexcore-remill`
   */
  decompileIr(irText: string): DecompileResult
  /** Check if the engine has been disposed. */
  get isDisposed(): boolean
}

/** Target architecture for the decompiler. */
export declare const enum Architecture {
  X86 = 0,
  X86_64 = 1,
  Arm = 2,
  Aarch64 = 3,
  Mips = 4,
  Mips64 = 5,
  PowerPc = 6,
  PowerPc64 = 7,
  Sparc = 8,
  Sparc64 = 9,
  Riscv32 = 10,
  Riscv64 = 11
}

/** Result of a decompilation operation. */
export interface DecompileResult {
  /** Decompiled pseudo-C source code. */
  source: string
  /** Function name. */
  functionName: string
  /** Entry address as hex string. */
  entryAddress: string
  /** Number of basic blocks in the CFG. */
  blockCount: number
  /** Number of instructions analyzed. */
  instructionCount: number
  /** Raw FlatBuffer data for the CFG (for Graph View zero-copy rendering). */
  cfgBuffer?: Buffer
  /** Raw FlatBuffer data for the AST (for AST View zero-copy rendering). */
  astBuffer?: Buffer
}

/**
 * Read the function name from a CFG FlatBuffer without full deserialization.
 *
 * Demonstrates zero-copy access — reads directly from the buffer.
 */
export declare function readCfgFunctionName(buffer: Buffer): string | null

/**
 * Serialize a decompiled AST into a FlatBuffer for the AST View.
 *
 * In Phase 1, this is a no-op returning an empty buffer.
 * In Phase 3+, this will use the `schemas/ast.fbs` generated code.
 */
export declare function serializeAst(astJson: string): Buffer

/**
 * Serialize a control flow graph into a FlatBuffer for the Graph View.
 *
 * In Phase 1, this is a no-op returning an empty buffer.
 * In Phase 3+, this will use the `schemas/cfg.fbs` generated code.
 */
export declare function serializeCfg(cfgJson: string): Buffer
