/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * The Helix decompilation engine.
 *
 * Usage from TypeScript:
 * ```typescript
 * import { HelixEngine, Architecture } from '@hexcore/helix';
 *
 * const engine = new HelixEngine(Architecture.X86_64);
 * const result = engine.decompileIr(irText);
 * console.log(result.source);  // pseudo-C from MLIR pipeline
 * engine.dispose();
 * ```
 */
export declare class HelixEngine {
  /** Create a new Helix engine instance for the specified architecture. */
  constructor(arch: Architecture)
  /** Get the engine version string. */
  version(): string
  /** Get the target architecture name. */
  architecture(): string
  /**
   * Decompile a binary buffer starting at the given entry address.
   *
   * - `data`: Raw binary data (Buffer)
   * - `base_address`: Base virtual address where the data is loaded (BigInt)
   * - `entry_address`: Entry point address to start decompilation (BigInt)
   */
  decompile(data: Buffer, baseAddress: bigint, entryAddress: bigint): DecompileResult
  /**
   * Decompile Remill LLVM IR text using the **C++ MLIR pipeline**.
   *
   * This is the **primary integration path** for the HexCore IDE.
   * Routes through: LLVM IR → MLIR translation → HelixLow → HelixHigh → Pseudo-C
   *
   * Falls back to the Rust pipeline if the MLIR engine is unavailable.
   */
  decompileIr(irText: string): DecompileResult
  /**
   * Decompile using the **pure Rust pipeline** (no C++ engine required).
   *
   * This is the fallback path and can be called directly for comparison.
   */
  decompileIrRust(irText: string): DecompileResult
  /**
   * Decompile Remill LLVM IR and return metrics alongside the result.
   *
   * Same as `decompile_ir` but also returns pipeline performance data.
   * Note: Metrics are currently from the Rust pipeline only.
   */
  decompileIrWithMetrics(irText: string): [DecompileResult, PipelineMetricsResult]
  /** Release engine resources. The engine cannot be used after this call. */
  dispose(): void
  /** Check if the engine has been disposed. */
  get isDisposed(): boolean
}

/** Target architecture for the decompiler. */
export declare const enum Architecture {
  X86 = 0,
  X86_64 = 1,
  Arm = 2,
  Aarch64 = 3,
  Mips = 4,
  Mips64 = 5,
  PowerPc = 6,
  PowerPc64 = 7,
  Sparc = 8,
  Sparc64 = 9,
  Riscv32 = 10,
  Riscv64 = 11
}

/** Result of a decompilation operation. */
export interface DecompileResult {
  /** Decompiled pseudo-C source code. */
  source: string
  /** Function name. */
  functionName: string
  /** Entry address as hex string. */
  entryAddress: string
  /** Number of basic blocks in the CFG. */
  blockCount: number
  /** Number of instructions analyzed. */
  instructionCount: number
  /** Raw FlatBuffer data for the CFG (for Graph View zero-copy rendering). */
  cfgBuffer?: Buffer
  /** Raw FlatBuffer data for the AST (for AST View zero-copy rendering). */
  astBuffer?: Buffer
  /** Which pipeline was used: "mlir" or "rust" */
  pipeline: string
}

/** Pipeline metrics exposed to JavaScript. */
export interface PipelineMetricsResult {
  /** Total pipeline duration in milliseconds. */
  totalMs: number
  /** Instructions decoded. */
  instructionsDecoded: number
  /** Functions recovered. */
  functionsRecovered: number
  /** Throughput in instructions per millisecond. */
  throughput: number
  /** Number of warnings. */
  warningCount: number
}

/**
 * Read the function name from a CFG FlatBuffer without full deserialization.
 *
 * Demonstrates zero-copy access — reads directly from the buffer.
 */
export declare function readCfgFunctionName(buffer: Buffer): string | null

/**
 * Serialize a decompiled AST into a FlatBuffer for the AST View.
 *
 * Takes a JSON string with AST data and returns a FlatBuffer binary.
 */
export declare function serializeAst(astJson: string): Buffer

/**
 * Serialize a control flow graph into a FlatBuffer for the Graph View.
 *
 * Takes a JSON string with CFG data and returns a FlatBuffer binary.
 */
export declare function serializeCfg(cfgJson: string): Buffer
