// Pseudo-C generated by HexCore Rellic
// Module: <string>
// Target: x86_64-unknown-windows-msvc-coff

#include <stdint.h>

void * lifted_5401711517(void * state, uint64_t program_counter, void * memory) {
	// Register variables
	uint64_t AL;
	uint64_t AX;
	uint64_t CL;
	uint64_t DIL;
	uint32_t EAX;
	uint32_t EBX;
	uint32_t EDX;
	uint64_t R8;
	uint64_t R9;
	uint64_t RAX;
	uint64_t RBX;
	uint64_t RCX;
	uint64_t RDI;
	uint64_t RDX;
	uint64_t RSP;


bb_0:
	NEXT_PC = program_counter;
	t0 = NEXT_PC;
	PC = t0;
	t1 = t0 + 6;
	NEXT_PC = t1;
	t2 = NEXT_PC;
	t3 = t2 + 0xccc9d;
	t4 = NEXT_PC;
	call(t5, t3, NEXT_PC, t4, RETURN_PC);  // CALL
	t7 = NEXT_PC;
	PC = t7;
	t8 = t7 + 5;
	NEXT_PC = t8;
	t9 = NEXT_PC;
	t10 = t9 + 0x2b70;
	t11 = NEXT_PC;
	call(t12, t10, NEXT_PC, t11, RETURN_PC);  // CALL
	t14 = NEXT_PC;
	PC = t14;
	t15 = t14 + 3;
	NEXT_PC = t15;
	t16 = RAX;
	t17 = RBX;  // MOV
	t19 = NEXT_PC;
	PC = t19;
	t20 = t19 + 4;
	NEXT_PC = t20;
	t21 = RAX;
	/* cmp t22, t21 */  // CMP
	t24 = NEXT_PC;
	PC = t24;
	t25 = t24 + 2;
	NEXT_PC = t25;
	t26 = NEXT_PC;
	t27 = t26 + 20;
	t28 = NEXT_PC;
	if (BRANCH_TAKEN) goto BRANCH_TAKEN; else goto t27;  // JZ
	t31 = NEXT_PC;
	PC = t31;
	t32 = t31 + 3;
	NEXT_PC = t32;
	t33 = RAX;
	t34 = RCX;  // MOV
	t36 = NEXT_PC;
	PC = t36;
	t37 = t36 + 5;
	NEXT_PC = t37;
	t38 = NEXT_PC;
	t39 = t38 - 0xcd9;
	t40 = NEXT_PC;
	call(t41, t39, NEXT_PC, t40, RETURN_PC);  // CALL
	t43 = NEXT_PC;
	PC = t43;
	t44 = t43 + 2;
	NEXT_PC = t44;
	t45 = AL;
	t46 = (uint64_t)t45;
	t47 = AL;
	t48 = (uint64_t)t47;
	/* test t49, t46 */  // TEST
	t51 = NEXT_PC;
	PC = t51;
	t52 = t51 + 2;
	NEXT_PC = t52;
	t53 = NEXT_PC;
	t54 = t53 + 8;
	t55 = NEXT_PC;
	if (BRANCH_TAKEN) goto BRANCH_TAKEN; else goto t54;  // JZ
	t58 = NEXT_PC;
	PC = t58;
	t59 = t58 + 3;
	NEXT_PC = t59;
	t60 = RBX;
	t61 = RCX;  // MOV
	t63 = NEXT_PC;
	PC = t63;
	t64 = t63 + 5;
	NEXT_PC = t64;
	t65 = NEXT_PC;
	t66 = t65 + 0x5564;
	t67 = NEXT_PC;
	call(t68, t66, NEXT_PC, t67, RETURN_PC);  // CALL
	t70 = NEXT_PC;
	PC = t70;
	t71 = t70 + 5;
	NEXT_PC = t71;
	t72 = NEXT_PC;
	t73 = t72 + 0x9a6;
	t74 = NEXT_PC;
	call(t75, t73, NEXT_PC, t74, RETURN_PC);  // CALL
	t77 = NEXT_PC;
	PC = t77;
	t78 = t77 + 3;
	NEXT_PC = t78;
	t79 = AX;
	t80 = (uint64_t)t79;
	MOVZX(t81, RBX, t80);
	t83 = NEXT_PC;
	PC = t83;
	t84 = t83 + 5;
	NEXT_PC = t84;
	t85 = NEXT_PC;
	t86 = t85 + 0x5539;
	t87 = NEXT_PC;
	call(t88, t86, NEXT_PC, t87, RETURN_PC);  // CALL
	t90 = NEXT_PC;
	PC = t90;
	t91 = t90 + 3;
	NEXT_PC = t91;
	t92 = RAX;
	t93 = R8;  // MOV
	t95 = NEXT_PC;
	PC = t95;
	t96 = t95 + 3;
	NEXT_PC = t96;
	t97 = EBX;
	t98 = (uint64_t)t97;
	t99 = R9;  // MOV
	t101 = NEXT_PC;
	PC = t101;
	t102 = t101 + 2;
	NEXT_PC = t102;
	t103 = RDX;
	t104 = EDX;
	t105 = (uint64_t)t104;
	t106 = RDX ^ t103;  // XOR
	t108 = NEXT_PC;
	PC = t108;
	t109 = t108 + 7;
	NEXT_PC = t109;
	t110 = NEXT_PC;
	t111 = t110 - 0x1f793e1;
	t112 = &RCX;  // LEA
	t114 = NEXT_PC;
	PC = t114;
	t115 = t114 + 5;
	NEXT_PC = t115;
	t116 = NEXT_PC;
	t117 = t116 - 0x1d47916;
	t118 = NEXT_PC;
	call(t119, t117, NEXT_PC, t118, RETURN_PC);  // CALL
	t121 = NEXT_PC;
	PC = t121;
	t122 = t121 + 2;
	NEXT_PC = t122;
	t123 = EAX;
	t124 = (uint64_t)t123;
	t125 = RBX;  // MOV
	t127 = NEXT_PC;
	PC = t127;
	t128 = t127 + 5;
	NEXT_PC = t128;
	t129 = NEXT_PC;
	t130 = t129 + 0x9cb;
	t131 = NEXT_PC;
	call(t132, t130, NEXT_PC, t131, RETURN_PC);  // CALL
	t134 = NEXT_PC;
	PC = t134;
	t135 = t134 + 2;
	NEXT_PC = t135;
	t136 = AL;
	t137 = (uint64_t)t136;
	t138 = AL;
	t139 = (uint64_t)t138;
	/* test t140, t137 */  // TEST
	t142 = NEXT_PC;
	PC = t142;
	t143 = t142 + 2;
	NEXT_PC = t143;
	t144 = NEXT_PC;
	t145 = t144 + 80;
	t146 = NEXT_PC;
	if (BRANCH_TAKEN) goto BRANCH_TAKEN; else goto t145;  // JZ
	t149 = NEXT_PC;
	PC = t149;
	t150 = t149 + 3;
	NEXT_PC = t150;
	t151 = DIL;
	t152 = (uint64_t)t151;
	t153 = DIL;
	t154 = (uint64_t)t153;
	/* test t155, t152 */  // TEST
	t157 = NEXT_PC;
	PC = t157;
	t158 = t157 + 2;
	NEXT_PC = t158;
	t159 = NEXT_PC;
	t160 = t159 + 5;
	t161 = NEXT_PC;
	if (!BRANCH_TAKEN) goto BRANCH_TAKEN; else goto t160;  // JNZ
	t164 = NEXT_PC;
	PC = t164;
	t165 = t164 + 5;
	NEXT_PC = t165;
	t166 = NEXT_PC;
	t167 = t166 + 0x54e6;
	t168 = NEXT_PC;
	call(t169, t167, NEXT_PC, t168, RETURN_PC);  // CALL
	t171 = NEXT_PC;
	PC = t171;
	t172 = t171 + 2;
	NEXT_PC = t172;
	t173 = RDX;
	t174 = EDX;
	t175 = (uint64_t)t174;
	t176 = RDX ^ t173;  // XOR
	t178 = NEXT_PC;
	PC = t178;
	t179 = t178 + 2;
	NEXT_PC = t179;
	t180 = CL;  // MOV
	t182 = NEXT_PC;
	PC = t182;
	t183 = t182 + 5;
	NEXT_PC = t183;
	t184 = NEXT_PC;
	t185 = t184 - 0xc64;
	t186 = NEXT_PC;
	call(t187, t185, NEXT_PC, t186, RETURN_PC);  // CALL
	t189 = NEXT_PC;
	PC = t189;
	t190 = t189 + 2;
	NEXT_PC = t190;
	t191 = EBX;
	t192 = (uint64_t)t191;
	t193 = RAX;  // MOV
	t195 = NEXT_PC;
	PC = t195;
	t196 = t195 + 2;
	NEXT_PC = t196;
	t197 = NEXT_PC;
	t198 = t197 + 25;
	goto t199;  // JMP
	t201 = NEXT_PC;
	PC = t201;
	t202 = t201 + 2;
	NEXT_PC = t202;
	t203 = EAX;
	t204 = (uint64_t)t203;
	t205 = RBX;  // MOV
	t207 = NEXT_PC;
	PC = t207;
	t208 = t207 + 5;
	NEXT_PC = t208;
	t209 = NEXT_PC;
	t210 = t209 + 0x9a9;
	t211 = NEXT_PC;
	call(t212, t210, NEXT_PC, t211, RETURN_PC);  // CALL
	t214 = NEXT_PC;
	PC = t214;
	t215 = t214 + 2;
	NEXT_PC = t215;
	t216 = AL;
	t217 = (uint64_t)t216;
	t218 = AL;
	t219 = (uint64_t)t218;
	/* test t220, t217 */  // TEST
	t222 = NEXT_PC;
	PC = t222;
	t223 = t222 + 2;
	NEXT_PC = t223;
	t224 = NEXT_PC;
	t225 = t224 + 54;
	t226 = NEXT_PC;
	if (BRANCH_TAKEN) goto BRANCH_TAKEN; else goto t225;  // JZ
	t229 = NEXT_PC;
	PC = t229;
	t230 = t229 + 5;
	NEXT_PC = t230;
	t231 = RSP;
	t232 = t231 + 32;
	/* cmp t233, t232 */  // CMP
	t235 = NEXT_PC;
	PC = t235;
	t236 = t235 + 2;
	NEXT_PC = t236;
	t237 = NEXT_PC;
	t238 = t237 + 5;
	t239 = NEXT_PC;
	if (!BRANCH_TAKEN) goto BRANCH_TAKEN; else goto t238;  // JNZ
	t242 = NEXT_PC;
	PC = t242;
	t243 = t242 + 5;
	NEXT_PC = t243;
	t244 = NEXT_PC;
	t245 = t244 + 0x5504;
	t246 = NEXT_PC;
	call(t247, t245, NEXT_PC, t246, RETURN_PC);  // CALL
	t249 = NEXT_PC;
	PC = t249;
	t250 = t249 + 2;
	NEXT_PC = t250;
	t251 = EBX;
	t252 = (uint64_t)t251;
	t253 = RAX;  // MOV
	t255 = NEXT_PC;
	PC = t255;
	t256 = t255 + 5;
	NEXT_PC = t256;
	t257 = RSP;
	t258 = t257 + 64;
	t259 = RBX;  // MOV
	t261 = NEXT_PC;
	PC = t261;
	t262 = t261 + 4;
	NEXT_PC = t262;
	t263 = RSP;
	t264 = RSP + t263;  // ADD
	t266 = NEXT_PC;
	PC = t266;
	t267 = t266 + 1;
	NEXT_PC = t267;
	t268 = *(uint64_t*)RSP; RSP += 8;  // POP
	t270 = NEXT_PC;
	PC = t270;
	t271 = t270 + 1;
	NEXT_PC = t271;
	return;  // RET
	t274 = NEXT_PC;
	PC = t274;
	t275 = t274 + 5;
	NEXT_PC = t275;
	t276 = RCX;  // MOV
	t278 = NEXT_PC;
	PC = t278;
	t279 = t278 + 5;
	NEXT_PC = t279;
	t280 = NEXT_PC;
	t281 = t280 + 0x7ee;
	t282 = NEXT_PC;
	call(t283, t281, NEXT_PC, t282, RETURN_PC);  // CALL
	t285 = NEXT_PC;
	PC = t285;
	t286 = t285 + 1;
	NEXT_PC = t286;
	/* nop */  // NOP_IMPL
	t289 = NEXT_PC;
	PC = t289;
	t290 = t289 + 5;
	NEXT_PC = t290;
	t291 = RCX;  // MOV
	t293 = NEXT_PC;
	PC = t293;
	t294 = t293 + 5;
	NEXT_PC = t294;
	t295 = NEXT_PC;
	t296 = t295 + 0x7e3;
	t297 = NEXT_PC;
	call(t298, t296, NEXT_PC, t297, RETURN_PC);  // CALL
	t300 = NEXT_PC;
	PC = t300;
	t301 = t300 + 2;
	NEXT_PC = t301;
	t302 = EBX;
	t303 = (uint64_t)t302;
	t304 = RCX;  // MOV
	t306 = NEXT_PC;
	PC = t306;
	t307 = t306 + 5;
	NEXT_PC = t307;
	t308 = NEXT_PC;
	t309 = t308 + 0x50e5;
	t310 = NEXT_PC;
	call(t311, t309, NEXT_PC, t310, RETURN_PC);  // CALL
	t313 = NEXT_PC;
	PC = t313;
	t314 = t313 + 1;
	NEXT_PC = t314;
	/* nop */  // NOP_IMPL
	t317 = NEXT_PC;
	PC = t317;
	t318 = t317 + 2;
	NEXT_PC = t318;
	t319 = EBX;
	t320 = (uint64_t)t319;
	t321 = RCX;  // MOV
	t323 = NEXT_PC;
	PC = t323;
	t324 = t323 + 5;
	NEXT_PC = t324;
	t325 = NEXT_PC;
	t326 = t325 + 0x541f;
	t327 = NEXT_PC;
	call(t328, t326, NEXT_PC, t327, RETURN_PC);  // CALL
	t330 = NEXT_PC;
	PC = t330;
	t331 = t330 + 1;
	NEXT_PC = t331;
	/* nop */  // NOP_IMPL
	t334 = NEXT_PC;
	PC = t334;
	t335 = t334 + 1;
	NEXT_PC = t335;
	DOINT3(t336, t338);
	t339 = NEXT_PC;
	PC = t339;
	t340 = t339 + 1;
	NEXT_PC = t340;
	DOINT3(t341, t338);
	t343 = NEXT_PC;
	PC = t343;
	t344 = t343 + 1;
	NEXT_PC = t344;
	DOINT3(t345, t338);
	t347 = NEXT_PC;
	PC = t347;
	t348 = t347 + 4;
	NEXT_PC = t348;
	t349 = RSP;
	t350 = RSP - t349;  // SUB
	t352 = NEXT_PC;
	PC = t352;
	t353 = t352 + 5;
	NEXT_PC = t353;
	t354 = NEXT_PC;
	t355 = t354 + 0x7ab;
	t356 = NEXT_PC;
	call(t357, t355, NEXT_PC, t356, RETURN_PC);  // CALL
	t359 = NEXT_PC;
	PC = t359;
	t360 = t359 + 2;
	NEXT_PC = t360;
	t361 = EAX;
	t362 = (uint64_t)t361;
	t363 = RCX;  // MOV
	t365 = NEXT_PC;
	PC = t365;
	t366 = t365 + 4;
	NEXT_PC = t366;
	t367 = RSP;
	t368 = RSP + t367;  // ADD
	t370 = NEXT_PC;
	PC = t370;
	t371 = t370 + 5;
	NEXT_PC = t371;
	t372 = NEXT_PC;
	t373 = t372 + 0x5497;
	goto t374;  // JMP
	t376 = NEXT_PC;
	PC = t376;
	t377 = t376 + 5;
	NEXT_PC = t377;
	t378 = NEXT_PC;
	t379 = t378 + 0x5498;
	goto t380;  // JMP
	t382 = NEXT_PC;
	PC = t382;
	t383 = t382 + 1;
	NEXT_PC = t383;
	DOINT3(t384, t338);
	t386 = NEXT_PC;
	PC = t386;
	t387 = t386 + 1;
	NEXT_PC = t387;
	DOINT3(t388, t338);
	t390 = NEXT_PC;
	PC = t390;
	t391 = t390 + 1;
	NEXT_PC = t391;
	DOINT3(t392, t338);
	t394 = NEXT_PC;
	PC = t394;
	t395 = t394 + 2;
	NEXT_PC = t395;
	t396 = RBX;
	RSP -= 8; *(uint64_t*)RSP = t397;  // PUSH
	t399 = NEXT_PC;
	PC = t399;
	t400 = t399 + 4;
	NEXT_PC = t400;
	t401 = RSP;
	t402 = RSP - t401;  // SUB
	t404 = NEXT_PC;
	PC = t404;
	t405 = t404 + 5;
	NEXT_PC = t405;
	t406 = NEXT_PC;
	t407 = t406 + 0x8f5;
	t408 = NEXT_PC;
	call(t409, t407, NEXT_PC, t408, RETURN_PC);  // CALL
	t411 = NEXT_PC;
	PC = t411;
	t412 = t411 + 3;
	NEXT_PC = t412;
	t413 = AX;
	t414 = (uint64_t)t413;
	MOVZX(t415, RBX, t414);
	t417 = NEXT_PC;
	PC = t417;
	t418 = t417 + 5;
	NEXT_PC = t418;
	t419 = NEXT_PC;
	t420 = t419 + 0x5488;
	t421 = NEXT_PC;
	call(t422, t420, NEXT_PC, t421, RETURN_PC);  // CALL
	t424 = NEXT_PC;
	PC = t424;
	t425 = t424 + 3;
	NEXT_PC = t425;
	t426 = RAX;
	t427 = R8;  // MOV
	t429 = NEXT_PC;
	PC = t429;
	t430 = t429 + 7;
	NEXT_PC = t430;
	t431 = NEXT_PC;
	t432 = t431 - 0x1f7948d;
	t433 = &RCX;  // LEA
	t435 = NEXT_PC;
	PC = t435;
	t436 = t435 + 3;
	NEXT_PC = t436;
	t437 = EBX;
	t438 = (uint64_t)t437;
	t439 = R9;  // MOV
	t441 = NEXT_PC;
	PC = t441;
	t442 = t441 + 2;
	NEXT_PC = t442;
	t443 = RDX;
	t444 = EDX;
	t445 = (uint64_t)t444;
	t446 = RDX ^ t443;  // XOR
	t448 = NEXT_PC;
	PC = t448;
	t449 = t448 + 4;
	NEXT_PC = t449;
	t450 = RSP;
	t451 = RSP + t450;  // ADD
	t453 = NEXT_PC;
	PC = t453;
	t454 = t453 + 1;
	NEXT_PC = t454;
	t455 = *(uint64_t*)RSP; RSP += 8;  // POP
	t457 = NEXT_PC;
	PC = t457;
	t458 = t457 + 5;
	NEXT_PC = t458;
	t459 = NEXT_PC;
	t460 = t459 - 0x1d479cc;
	goto t461;  // JMP
	return memory;
}

